-- APEXCORE SOVEREIGN FINANCIAL LEDGER (ACID COMPLIANT)
CREATE TABLE apex_wallets (
    user_id BIGINT PRIMARY KEY,
    available_balance NUMERIC(36, 18) NOT NULL DEFAULT 0,
    locked_balance NUMERIC(36, 18) NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
